package com.guifa.paper;

public class Constant {
    public static final String jsonStr = "{\n" +
            "\"page_name\":\"要闻\",\n" +
            "\"page_num\":\"01\",\n" +
            "\"period_num\":\"2019-04-13\",\n" +
            "\"page_pic\":\"https://rmrbcmsonline.peopleapp.com/upload/image/201904/201904130450041113.jpg?x-oss-process=image/resize,w_500\",\n" +
            "\"page_time\":1555270132,\n" +
            "\"items\":[\n" +
            "{\n" +
            "\"points\":\"1047,139;1047,7;538,7;538,139;538,238;1047,238\",\n" +
            "\"title\":\"习近平电贺金正恩再次就任朝鲜国务委员会委员长\",\n" +
            "\"id\":4052556,\n" +
            "\"articleid\":3909557,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":[\n" +
            "],\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_2\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"7,259;512,259;512,768;7,768\",\n" +
            "\"title\":\"中关村 创新脚步从未停歇（壮丽70年·奋斗新时代）\",\n" +
            "\"id\":4052557,\n" +
            "\"articleid\":3909558,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":\"本报记者 朱竞若 王昊男\",\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_2\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"538,259;1047,259;1047,636;538,636\",\n" +
            "\"title\":\"努力创造更加美好的明天\",\n" +
            "\"id\":4052558,\n" +
            "\"articleid\":3909559,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":\"本报记者 张 帆 徐元锋 杨文明\",\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_2\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"538,663;1047,663;1047,1028;538,1028\",\n" +
            "\"title\":\"李克强出席第八次中国—中东欧国家领导人会晤\",\n" +
            "\"id\":4052559,\n" +
            "\"articleid\":3909560,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":[\n" +
            "],\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"image\":[\n" +
            "\"https://rmrbcmsonline.peopleapp.com/upload/image/201904/201904130450234768.jpg?x-oss-process=style/w10\"\n" +
            "],\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_3\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"515,883;515,790;7,790;7,883;7,1021;515,1021\",\n" +
            "\"title\":\"栗战书主持召开第二十八次委员长会议\",\n" +
            "\"id\":4052560,\n" +
            "\"articleid\":3909561,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":[\n" +
            "],\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_2\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"18,1040;519,1040;519,1524;18,1524\",\n" +
            "\"title\":\"一季度外贸开局平稳（礼赞70年）\",\n" +
            "\"id\":4052561,\n" +
            "\"articleid\":3909562,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":[\n" +
            "],\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"image\":[\n" +
            "\"https://rmrbcmsonline.peopleapp.com/upload/image/201904/201904130450248232.jpg?x-oss-process=style/w10\"\n" +
            "],\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_3\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"1047,1148;1047,1055;538,1055;538,1148;538,1287;1047,1287\",\n" +
            "\"title\":\"全国政协召开双周协商座谈会\",\n" +
            "\"id\":4052562,\n" +
            "\"articleid\":3909563,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":[\n" +
            "],\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_2\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "},\n" +
            "{\n" +
            "\"points\":\"1047,1437;1047,1304;538,1304;538,1437;538,1537;1047,1537\",\n" +
            "\"title\":\"切实增强政治责任感和历史使命感 加快形成国土绿化事业发展新格局\",\n" +
            "\"id\":4052563,\n" +
            "\"articleid\":3909564,\n" +
            "\"category_id\":\"115\",\n" +
            "\"authors\":[\n" +
            "],\n" +
            "\"news_timestamp\":1555084800,\n" +
            "\"news_datetime\":\"2019-04-13\",\n" +
            "\"comment_count\":0,\n" +
            "\"view_type\":\"paper_2\",\n" +
            "\"title_style\":null,\n" +
            "\"description\":null,\n" +
            "\"copyfrom\":null,\n" +
            "\"news_link\":null,\n" +
            "\"medias\":null,\n" +
            "\"content\":null\n" +
            "}\n" +
            "]\n" +
            "}";
}